# Generated by Django 5.1.1 on 2024-09-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=6, unique=True)),
                ('file_url', models.URLField()),
                ('original_file_name', models.CharField(max_length=255)),
            ],
        ),
    ]
